//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class accession_ipr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accession_ipr()
        {
            this.citations = new HashSet<citation>();
        }
    
        public int accession_ipr_id { get; set; }
        public int accession_id { get; set; }
        public string type_code { get; set; }
        public string ipr_number { get; set; }
        public string ipr_crop_name { get; set; }
        public string ipr_full_name { get; set; }
        public Nullable<System.DateTime> issued_date { get; set; }
        public Nullable<System.DateTime> expired_date { get; set; }
        public Nullable<int> cooperator_id { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> accepted_date { get; set; }
        public Nullable<System.DateTime> expected_date { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual accession accession { get; set; }
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual cooperator cooperator3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<citation> citations { get; set; }
    }
}
