//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class accession_inv_annotation
    {
        public int accession_inv_annotation_id { get; set; }
        public string annotation_type_code { get; set; }
        public System.DateTime annotation_date { get; set; }
        public string annotation_date_code { get; set; }
        public Nullable<int> annotation_cooperator_id { get; set; }
        public int inventory_id { get; set; }
        public Nullable<int> order_request_id { get; set; }
        public Nullable<int> old_taxonomy_species_id { get; set; }
        public Nullable<int> new_taxonomy_species_id { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual inventory inventory { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual order_request order_request { get; set; }
        public virtual cooperator cooperator3 { get; set; }
        public virtual taxonomy_species taxonomy_species { get; set; }
        public virtual taxonomy_species taxonomy_species1 { get; set; }
    }
}
