//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class accession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accession()
        {
            this.accession_action = new HashSet<accession_action>();
            this.accession_pedigree = new HashSet<accession_pedigree>();
            this.accession_pedigree1 = new HashSet<accession_pedigree>();
            this.accession_pedigree2 = new HashSet<accession_pedigree>();
            this.accession_quarantine = new HashSet<accession_quarantine>();
            this.accession_ipr = new HashSet<accession_ipr>();
            this.accession_source = new HashSet<accession_source>();
            this.citations = new HashSet<citation>();
            this.inventories = new HashSet<inventory>();
            this.web_order_request_item = new HashSet<web_order_request_item>();
            this.web_user_cart_item = new HashSet<web_user_cart_item>();
        }
    
        public int accession_id { get; set; }
        public string doi { get; set; }
        public string accession_number_part1 { get; set; }
        public Nullable<int> accession_number_part2 { get; set; }
        public string accession_number_part3 { get; set; }
        public string is_core { get; set; }
        public string is_backed_up { get; set; }
        public Nullable<int> backup_location1_site_id { get; set; }
        public Nullable<int> backup_location2_site_id { get; set; }
        public string status_code { get; set; }
        public string life_form_code { get; set; }
        public string improvement_status_code { get; set; }
        public string reproductive_uniformity_code { get; set; }
        public string initial_received_form_code { get; set; }
        public Nullable<System.DateTime> initial_received_date { get; set; }
        public string initial_received_date_code { get; set; }
        public int taxonomy_species_id { get; set; }
        public string is_web_visible { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual site site { get; set; }
        public virtual site site1 { get; set; }
        public virtual taxonomy_species taxonomy_species { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accession_action> accession_action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accession_pedigree> accession_pedigree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accession_pedigree> accession_pedigree1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accession_pedigree> accession_pedigree2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accession_quarantine> accession_quarantine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accession_ipr> accession_ipr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accession_source> accession_source { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<citation> citations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory> inventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request_item> web_order_request_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user_cart_item> web_user_cart_item { get; set; }
    }
}
