//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class crop_trait
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crop_trait()
        {
            this.crop_trait_attach = new HashSet<crop_trait_attach>();
            this.crop_trait_lang = new HashSet<crop_trait_lang>();
            this.crop_trait_observation = new HashSet<crop_trait_observation>();
            this.crop_trait_observation_data = new HashSet<crop_trait_observation_data>();
            this.feedback_form_trait = new HashSet<feedback_form_trait>();
            this.feedback_result_trait_obs = new HashSet<feedback_result_trait_obs>();
            this.crop_trait_code = new HashSet<crop_trait_code>();
        }
    
        public int crop_trait_id { get; set; }
        public int crop_id { get; set; }
        public string coded_name { get; set; }
        public string is_peer_reviewed { get; set; }
        public string category_code { get; set; }
        public string data_type_code { get; set; }
        public string is_coded { get; set; }
        public Nullable<int> max_length { get; set; }
        public string numeric_format { get; set; }
        public Nullable<decimal> numeric_maximum { get; set; }
        public Nullable<decimal> numeric_minimum { get; set; }
        public string original_value_type_code { get; set; }
        public string original_value_format { get; set; }
        public string is_archived { get; set; }
        public string ontology_url { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual crop crop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crop_trait_attach> crop_trait_attach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crop_trait_lang> crop_trait_lang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crop_trait_observation> crop_trait_observation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crop_trait_observation_data> crop_trait_observation_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feedback_form_trait> feedback_form_trait { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feedback_result_trait_obs> feedback_result_trait_obs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crop_trait_code> crop_trait_code { get; set; }
    }
}
