//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class email
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public email()
        {
            this.email_attach = new HashSet<email_attach>();
        }
    
        public int email_id { get; set; }
        public string id_type { get; set; }
        public Nullable<int> id_number { get; set; }
        public string email_from { get; set; }
        public string email_to { get; set; }
        public string email_cc { get; set; }
        public string email_bcc { get; set; }
        public string email_reply_to { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public string is_html { get; set; }
        public System.DateTime to_be_sent_date { get; set; }
        public Nullable<System.DateTime> sent_date { get; set; }
        public int retry_count { get; set; }
        public Nullable<System.DateTime> last_retry_date { get; set; }
        public string last_retry_error_message { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<email_attach> email_attach { get; set; }
    }
}
