//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class exploration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public exploration()
        {
            this.exploration_map = new HashSet<exploration_map>();
        }
    
        public int exploration_id { get; set; }
        public string exploration_number { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> began_date { get; set; }
        public Nullable<System.DateTime> finished_date { get; set; }
        public string funding_source { get; set; }
        public Nullable<decimal> funding_amount { get; set; }
        public string target_species { get; set; }
        public string permits { get; set; }
        public string restrictions { get; set; }
        public Nullable<int> fiscal_year { get; set; }
        public Nullable<int> host_cooperator_id { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual cooperator cooperator3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exploration_map> exploration_map { get; set; }
    }
}
