//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback_report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public feedback_report()
        {
            this.feedback_report_attach = new HashSet<feedback_report_attach>();
            this.feedback_result_group = new HashSet<feedback_result_group>();
        }
    
        public int feedback_report_id { get; set; }
        public int feedback_id { get; set; }
        public int feedback_form_id { get; set; }
        public string title { get; set; }
        public string is_observation_data { get; set; }
        public string is_web_visible { get; set; }
        public int due_interval { get; set; }
        public string interval_length_code { get; set; }
        public string interval_type_code { get; set; }
        public Nullable<System.DateTime> custom_due_date { get; set; }
        public int sort_order { get; set; }
        public string is_notified_initially { get; set; }
        public string is_notified_30days_prior { get; set; }
        public string is_notified_15days_prior { get; set; }
        public string initial_email_text { get; set; }
        public string initial_email_subject { get; set; }
        public string prior30_email_text { get; set; }
        public string prior30_email_subject { get; set; }
        public string prior15_email_text { get; set; }
        public string prior15_email_subject { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual feedback feedback { get; set; }
        public virtual feedback_form feedback_form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feedback_report_attach> feedback_report_attach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feedback_result_group> feedback_result_group { get; set; }
    }
}
