//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback_form_field
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public feedback_form_field()
        {
            this.feedback_result_field = new HashSet<feedback_result_field>();
        }
    
        public int feedback_form_field_id { get; set; }
        public int feedback_form_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string field_type_code { get; set; }
        public string gui_hint { get; set; }
        public string foreign_key_dataview_name { get; set; }
        public string group_name { get; set; }
        public Nullable<int> sort_order { get; set; }
        public string is_readonly { get; set; }
        public string is_required { get; set; }
        public string references_tag { get; set; }
        public string default_value { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual feedback_form feedback_form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feedback_result_field> feedback_result_field { get; set; }
    }
}
