//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class genetic_marker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public genetic_marker()
        {
            this.citations = new HashSet<citation>();
            this.genetic_annotation = new HashSet<genetic_annotation>();
        }
    
        public int genetic_marker_id { get; set; }
        public int crop_id { get; set; }
        public string name { get; set; }
        public string synonyms { get; set; }
        public string repeat_motif { get; set; }
        public string primers { get; set; }
        public string assay_conditions { get; set; }
        public string range_products { get; set; }
        public string genbank_number { get; set; }
        public string known_standards { get; set; }
        public string map_location { get; set; }
        public string position { get; set; }
        public string poly_type_code { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<citation> citations { get; set; }
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual crop crop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genetic_annotation> genetic_annotation { get; set; }
    }
}
