//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class genetic_annotation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public genetic_annotation()
        {
            this.genetic_observation = new HashSet<genetic_observation>();
            this.genetic_observation_data = new HashSet<genetic_observation_data>();
        }
    
        public int genetic_annotation_id { get; set; }
        public int genetic_marker_id { get; set; }
        public int method_id { get; set; }
        public string assay_method { get; set; }
        public string scoring_method { get; set; }
        public string control_values { get; set; }
        public Nullable<int> observation_alleles_count { get; set; }
        public Nullable<int> max_gob_alleles { get; set; }
        public string size_alleles { get; set; }
        public string unusual_alleles { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual genetic_marker genetic_marker { get; set; }
        public virtual method method { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genetic_observation> genetic_observation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genetic_observation_data> genetic_observation_data { get; set; }
    }
}
