//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class genetic_observation_data
    {
        public int genetic_observation_data_id { get; set; }
        public Nullable<int> genetic_observation_id { get; set; }
        public int genetic_annotation_id { get; set; }
        public int inventory_id { get; set; }
        public Nullable<int> individual { get; set; }
        public Nullable<int> individual_allele_number { get; set; }
        public string value { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual genetic_annotation genetic_annotation { get; set; }
        public virtual genetic_observation genetic_observation { get; set; }
        public virtual inventory inventory { get; set; }
    }
}
