//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class geography
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public geography()
        {
            this.accession_source = new HashSet<accession_source>();
            this.cooperators = new HashSet<cooperator>();
            this.cooperators1 = new HashSet<cooperator>();
            this.geography1 = new HashSet<geography>();
            this.geography_region_map = new HashSet<geography_region_map>();
            this.methods = new HashSet<method>();
            this.taxonomy_geography_map = new HashSet<taxonomy_geography_map>();
            this.taxonomy_noxious = new HashSet<taxonomy_noxious>();
            this.web_cooperator = new HashSet<web_cooperator>();
            this.web_order_request_address = new HashSet<web_order_request_address>();
            this.web_user_shipping_address = new HashSet<web_user_shipping_address>();
        }
    
        public int geography_id { get; set; }
        public Nullable<int> current_geography_id { get; set; }
        public string country_code { get; set; }
        public string adm1 { get; set; }
        public string adm1_type_code { get; set; }
        public string adm1_abbrev { get; set; }
        public string adm2 { get; set; }
        public string adm2_type_code { get; set; }
        public string adm2_abbrev { get; set; }
        public string adm3 { get; set; }
        public string adm3_type_code { get; set; }
        public string adm3_abbrev { get; set; }
        public string adm4 { get; set; }
        public string adm4_type_code { get; set; }
        public string adm4_abbrev { get; set; }
        public Nullable<System.DateTime> changed_date { get; set; }
        public string is_valid { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accession_source> accession_source { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cooperator> cooperators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cooperator> cooperators1 { get; set; }
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<geography> geography1 { get; set; }
        public virtual geography geography2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<geography_region_map> geography_region_map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<method> methods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taxonomy_geography_map> taxonomy_geography_map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taxonomy_noxious> taxonomy_noxious { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_cooperator> web_cooperator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request_address> web_order_request_address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user_shipping_address> web_user_shipping_address { get; set; }
    }
}
