//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_maint_policy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inventory_maint_policy()
        {
            this.inventories = new HashSet<inventory>();
        }
    
        public int inventory_maint_policy_id { get; set; }
        public string maintenance_name { get; set; }
        public string form_type_code { get; set; }
        public string quantity_on_hand_unit_code { get; set; }
        public string web_availability_note { get; set; }
        public string is_auto_deducted { get; set; }
        public string distribution_default_form_code { get; set; }
        public Nullable<decimal> distribution_default_quantity { get; set; }
        public string distribution_unit_code { get; set; }
        public Nullable<decimal> distribution_critical_quantity { get; set; }
        public Nullable<decimal> regeneration_critical_quantity { get; set; }
        public string regeneration_method_code { get; set; }
        public Nullable<int> curator_cooperator_id { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual cooperator cooperator3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory> inventories { get; set; }
    }
}
