//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_viability_data
    {
        public int inventory_viability_data_id { get; set; }
        public int inventory_viability_id { get; set; }
        public Nullable<int> order_request_item_id { get; set; }
        public Nullable<int> counter_cooperator_id { get; set; }
        public int replication_number { get; set; }
        public int count_number { get; set; }
        public System.DateTime count_date { get; set; }
        public int normal_count { get; set; }
        public Nullable<int> abnormal_count { get; set; }
        public Nullable<int> dormant_count { get; set; }
        public Nullable<int> hard_count { get; set; }
        public Nullable<int> empty_count { get; set; }
        public Nullable<int> infested_count { get; set; }
        public Nullable<int> dead_count { get; set; }
        public Nullable<int> unknown_count { get; set; }
        public Nullable<int> estimated_dormant_count { get; set; }
        public Nullable<int> treated_dormant_count { get; set; }
        public Nullable<int> confirmed_dormant_count { get; set; }
        public Nullable<int> replication_count { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual cooperator cooperator3 { get; set; }
        public virtual inventory_viability inventory_viability { get; set; }
        public virtual order_request_item order_request_item { get; set; }
    }
}
