//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_quality_status
    {
        public int inventory_quality_status_id { get; set; }
        public int inventory_id { get; set; }
        public string test_type_code { get; set; }
        public string contaminant_code { get; set; }
        public string test_result_code { get; set; }
        public string plant_part_tested_code { get; set; }
        public string test_results_score { get; set; }
        public string test_results_score_type_code { get; set; }
        public Nullable<decimal> negative_control { get; set; }
        public Nullable<decimal> positive_control { get; set; }
        public Nullable<int> replicate { get; set; }
        public Nullable<System.DateTime> started_date { get; set; }
        public string started_date_code { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public string completed_date_code { get; set; }
        public Nullable<int> required_replication_count { get; set; }
        public Nullable<int> started_count { get; set; }
        public Nullable<int> completed_count { get; set; }
        public string plate_or_assay_number { get; set; }
        public Nullable<int> method_id { get; set; }
        public Nullable<int> tester_cooperator_id { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual cooperator cooperator3 { get; set; }
        public virtual inventory inventory { get; set; }
        public virtual method method { get; set; }
    }
}
