//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_viability_rule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inventory_viability_rule()
        {
            this.inventory_viability = new HashSet<inventory_viability>();
            this.inventory_viability_rule_map = new HashSet<inventory_viability_rule_map>();
        }
    
        public int inventory_viability_rule_id { get; set; }
        public string name { get; set; }
        public string substrata { get; set; }
        public Nullable<int> seeds_per_replicate { get; set; }
        public Nullable<int> number_of_replicates { get; set; }
        public string requirements { get; set; }
        public string category_code { get; set; }
        public string temperature_range { get; set; }
        public string count_regime_days { get; set; }
        public string moisture { get; set; }
        public string prechill { get; set; }
        public string lighting { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_viability> inventory_viability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_viability_rule_map> inventory_viability_rule_map { get; set; }
    }
}
