//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_viability
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inventory_viability()
        {
            this.inventory_viability_data = new HashSet<inventory_viability_data>();
        }
    
        public int inventory_viability_id { get; set; }
        public int inventory_id { get; set; }
        public Nullable<int> inventory_viability_rule_id { get; set; }
        public System.DateTime tested_date { get; set; }
        public string tested_date_code { get; set; }
        public Nullable<int> percent_normal { get; set; }
        public Nullable<int> percent_abnormal { get; set; }
        public Nullable<int> percent_dormant { get; set; }
        public Nullable<int> percent_viable { get; set; }
        public Nullable<int> percent_hard { get; set; }
        public Nullable<int> percent_empty { get; set; }
        public Nullable<int> percent_infested { get; set; }
        public Nullable<int> percent_dead { get; set; }
        public Nullable<int> percent_unknown { get; set; }
        public string vigor_rating_code { get; set; }
        public Nullable<int> total_tested_count { get; set; }
        public Nullable<int> replication_count { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual inventory inventory { get; set; }
        public virtual inventory_viability_rule inventory_viability_rule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_viability_data> inventory_viability_data { get; set; }
    }
}
