//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inventory()
        {
            this.accession_inv_annotation = new HashSet<accession_inv_annotation>();
            this.accession_inv_attach = new HashSet<accession_inv_attach>();
            this.accession_inv_group_map = new HashSet<accession_inv_group_map>();
            this.accession_inv_name = new HashSet<accession_inv_name>();
            this.accession_inv_voucher = new HashSet<accession_inv_voucher>();
            this.crop_trait_observation = new HashSet<crop_trait_observation>();
            this.crop_trait_observation_data = new HashSet<crop_trait_observation_data>();
            this.feedback_inventory = new HashSet<feedback_inventory>();
            this.feedback_result = new HashSet<feedback_result>();
            this.feedback_result_trait_obs = new HashSet<feedback_result_trait_obs>();
            this.genetic_observation = new HashSet<genetic_observation>();
            this.genetic_observation_data = new HashSet<genetic_observation_data>();
            this.geneva_site_inventory = new HashSet<geneva_site_inventory>();
            this.gspi_site_inventory = new HashSet<gspi_site_inventory>();
            this.gspi_site_inventory1 = new HashSet<gspi_site_inventory>();
            this.inventory1 = new HashSet<inventory>();
            this.inventory11 = new HashSet<inventory>();
            this.inventory_action = new HashSet<inventory_action>();
            this.inventory_quality_status = new HashSet<inventory_quality_status>();
            this.inventory_viability = new HashSet<inventory_viability>();
            this.nc7_site_inventory = new HashSet<nc7_site_inventory>();
            this.ne9_site_inventory = new HashSet<ne9_site_inventory>();
            this.nssl_site_inventory = new HashSet<nssl_site_inventory>();
            this.opgc_site_inventory = new HashSet<opgc_site_inventory>();
            this.order_request_item = new HashSet<order_request_item>();
            this.parl_site_inventory = new HashSet<parl_site_inventory>();
            this.s9_site_inventory = new HashSet<s9_site_inventory>();
            this.w6_site_inventory = new HashSet<w6_site_inventory>();
            this.w6_site_inventory1 = new HashSet<w6_site_inventory>();
        }
    
        public int inventory_id { get; set; }
        public string inventory_number_part1 { get; set; }
        public Nullable<int> inventory_number_part2 { get; set; }
        public string inventory_number_part3 { get; set; }
        public string form_type_code { get; set; }
        public int inventory_maint_policy_id { get; set; }
        public string is_distributable { get; set; }
        public string storage_location_part1 { get; set; }
        public string storage_location_part2 { get; set; }
        public string storage_location_part3 { get; set; }
        public string storage_location_part4 { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public string is_available { get; set; }
        public string web_availability_note { get; set; }
        public string availability_status_code { get; set; }
        public string availability_status_note { get; set; }
        public Nullable<System.DateTime> availability_start_date { get; set; }
        public Nullable<System.DateTime> availability_end_date { get; set; }
        public Nullable<decimal> quantity_on_hand { get; set; }
        public string quantity_on_hand_unit_code { get; set; }
        public string is_auto_deducted { get; set; }
        public string distribution_default_form_code { get; set; }
        public Nullable<decimal> distribution_default_quantity { get; set; }
        public string distribution_unit_code { get; set; }
        public Nullable<decimal> distribution_critical_quantity { get; set; }
        public Nullable<decimal> regeneration_critical_quantity { get; set; }
        public string pathogen_status_code { get; set; }
        public int accession_id { get; set; }
        public Nullable<int> parent_inventory_id { get; set; }
        public Nullable<int> backup_inventory_id { get; set; }
        public string rootstock { get; set; }
        public Nullable<decimal> hundred_seed_weight { get; set; }
        public string pollination_method_code { get; set; }
        public string pollination_vector_code { get; set; }
        public Nullable<int> preservation_method_id { get; set; }
        public Nullable<int> regeneration_method_id { get; set; }
        public string plant_sex_code { get; set; }
        public Nullable<System.DateTime> propagation_date { get; set; }
        public string propagation_date_code { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual accession accession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accession_inv_annotation> accession_inv_annotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accession_inv_attach> accession_inv_attach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accession_inv_group_map> accession_inv_group_map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accession_inv_name> accession_inv_name { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accession_inv_voucher> accession_inv_voucher { get; set; }
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crop_trait_observation> crop_trait_observation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crop_trait_observation_data> crop_trait_observation_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feedback_inventory> feedback_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feedback_result> feedback_result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feedback_result_trait_obs> feedback_result_trait_obs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genetic_observation> genetic_observation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genetic_observation_data> genetic_observation_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<geneva_site_inventory> geneva_site_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gspi_site_inventory> gspi_site_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gspi_site_inventory> gspi_site_inventory1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory> inventory1 { get; set; }
        public virtual inventory inventory2 { get; set; }
        public virtual inventory_maint_policy inventory_maint_policy { get; set; }
        public virtual method method { get; set; }
        public virtual method method1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory> inventory11 { get; set; }
        public virtual inventory inventory3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_action> inventory_action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_quality_status> inventory_quality_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_viability> inventory_viability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nc7_site_inventory> nc7_site_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ne9_site_inventory> ne9_site_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nssl_site_inventory> nssl_site_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<opgc_site_inventory> opgc_site_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_request_item> order_request_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parl_site_inventory> parl_site_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s9_site_inventory> s9_site_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<w6_site_inventory> w6_site_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<w6_site_inventory> w6_site_inventory1 { get; set; }
    }
}
