//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class nc7_site_inventory
    {
        public int nc7_site_inventory_id { get; set; }
        public int inventory_id { get; set; }
        public Nullable<decimal> hundred_weight { get; set; }
        public string pollination_control_code { get; set; }
        public string farm_field_identifier_code { get; set; }
        public string location_type_code { get; set; }
        public string location_low { get; set; }
        public string location_high { get; set; }
        public string sublocation_type_code { get; set; }
        public string sublocation_low { get; set; }
        public string sublocation_high { get; set; }
        public string old_inventory_identifier { get; set; }
        public string inventory_site_note { get; set; }
        public Nullable<decimal> inventory_location1_latitude { get; set; }
        public Nullable<decimal> inventory_location1_longitude { get; set; }
        public Nullable<int> inventory_location1_precision { get; set; }
        public Nullable<decimal> inventory_location2_latitude { get; set; }
        public Nullable<decimal> inventory_location2_longitude { get; set; }
        public Nullable<int> inventory_location2_precision { get; set; }
        public string inventory_datum_code { get; set; }
        public string coordinates_apply_to_code { get; set; }
        public string coordinates_comment { get; set; }
        public string coordinates_voucher_location { get; set; }
        public string irregular_inventory_location { get; set; }
        public string is_increase_success_flag { get; set; }
        public string reason_unsuccessfull1_code { get; set; }
        public string reason_unsuccessfull2_code { get; set; }
        public string reason_unsuccessfull3_code { get; set; }
        public string reason_unsuccessfull_note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual inventory inventory { get; set; }
    }
}
