//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class nssl_site_inventory
    {
        public int nssl_site_inventory_id { get; set; }
        public int inventory_id { get; set; }
        public string next_test { get; set; }
        public Nullable<decimal> hundred_weight { get; set; }
        public Nullable<decimal> moisture_1 { get; set; }
        public string moisture_1_type_code { get; set; }
        public Nullable<System.DateTime> moisture_1_date { get; set; }
        public Nullable<decimal> moisture_2 { get; set; }
        public string moisture_2_type_code { get; set; }
        public Nullable<System.DateTime> moisture_2_date { get; set; }
        public Nullable<decimal> moisture_3 { get; set; }
        public string moisture_3_type_code { get; set; }
        public Nullable<System.DateTime> moisture_3_date { get; set; }
        public Nullable<decimal> moisture_4 { get; set; }
        public string moisture_4_type_code { get; set; }
        public Nullable<System.DateTime> moisture_4_date { get; set; }
        public Nullable<decimal> moisture_5 { get; set; }
        public string moisture_5_type_code { get; set; }
        public Nullable<System.DateTime> moisture_5_date { get; set; }
        public Nullable<decimal> percent_cleanout { get; set; }
        public Nullable<int> estimated_in_LN2 { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual inventory inventory { get; set; }
    }
}
