//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_request()
        {
            this.accession_inv_annotation = new HashSet<accession_inv_annotation>();
            this.order_request1 = new HashSet<order_request>();
            this.order_request_action = new HashSet<order_request_action>();
            this.order_request_attach = new HashSet<order_request_attach>();
            this.order_request_item = new HashSet<order_request_item>();
            this.order_request_phyto_log = new HashSet<order_request_phyto_log>();
        }
    
        public int order_request_id { get; set; }
        public Nullable<int> original_order_request_id { get; set; }
        public Nullable<int> web_order_request_id { get; set; }
        public string local_number { get; set; }
        public string order_type_code { get; set; }
        public Nullable<System.DateTime> ordered_date { get; set; }
        public string intended_use_code { get; set; }
        public string intended_use_note { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public Nullable<int> requestor_cooperator_id { get; set; }
        public Nullable<int> ship_to_cooperator_id { get; set; }
        public int final_recipient_cooperator_id { get; set; }
        public string order_obtained_via { get; set; }
        public Nullable<int> feedback_id { get; set; }
        public string special_instruction { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accession_inv_annotation> accession_inv_annotation { get; set; }
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual cooperator cooperator3 { get; set; }
        public virtual cooperator cooperator4 { get; set; }
        public virtual cooperator cooperator5 { get; set; }
        public virtual feedback feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_request> order_request1 { get; set; }
        public virtual order_request order_request2 { get; set; }
        public virtual web_order_request web_order_request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_request_action> order_request_action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_request_attach> order_request_attach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_request_item> order_request_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_request_phyto_log> order_request_phyto_log { get; set; }
    }
}
