//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_request_phyto_log
    {
        public int order_request_phyto_log_id { get; set; }
        public int order_request_id { get; set; }
        public System.DateTime received_date { get; set; }
        public Nullable<System.DateTime> opened_date { get; set; }
        public string number_of_packages { get; set; }
        public Nullable<int> number_of_items { get; set; }
        public string major_genus { get; set; }
        public string import_permit_identifier { get; set; }
        public Nullable<System.DateTime> setup_inspection_date { get; set; }
        public Nullable<System.DateTime> inspected_date { get; set; }
        public Nullable<int> inspected_by_cooperator_id { get; set; }
        public string phyto_certificate_type_code { get; set; }
        public Nullable<int> certificate_cost { get; set; }
        public string phyto_certificate_identifier { get; set; }
        public Nullable<System.DateTime> shipped_date { get; set; }
        public string shipping_carrier { get; set; }
        public string tracking_identifier { get; set; }
        public string passed_inspection { get; set; }
        public string delivered { get; set; }
        public Nullable<System.DateTime> delivered_date { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual cooperator cooperator3 { get; set; }
        public virtual order_request order_request { get; set; }
    }
}
