//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class plant_inventory_index
    {
        public int plant_inventory_index_id { get; set; }
        public int plant_inventory_volumn { get; set; }
        public int plant_inventory_page { get; set; }
        public int first_number { get; set; }
        public int last_number { get; set; }
        public int page_offset { get; set; }
        public string volumn_suffix { get; set; }
    }
}
