//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class plant_immigrant_index
    {
        public int plant_immigrant_index_id { get; set; }
        public int plant_immigrant_volumn { get; set; }
        public int first_number { get; set; }
        public int last_number { get; set; }
        public int plant_immigrant_page { get; set; }
    }
}
