//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class pvpo_catalog_bak
    {
        public int pvpo_catalog_id { get; set; }
        public Nullable<int> PVNUMBER { get; set; }
        public string VARIETY { get; set; }
        public string EXPERMENTALNAMESYNONYMS { get; set; }
        public string TAXON { get; set; }
        public string CROP { get; set; }
        public string APPLICANTOWNER { get; set; }
        public string APPLICATIONDATE { get; set; }
        public string CERTIFIEDSEED { get; set; }
        public string STATUS { get; set; }
        public string STATUSDATE { get; set; }
        public string DATEISSUED { get; set; }
        public Nullable<int> YEARSPROTECTED { get; set; }
        public Nullable<int> PAGES { get; set; }
        public string REFILEDUNDER1994PVPA { get; set; }
        public string AMENDMENTS { get; set; }
    }
}
