//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class source_descriptor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public source_descriptor()
        {
            this.source_desc_observation = new HashSet<source_desc_observation>();
            this.source_descriptor_code = new HashSet<source_descriptor_code>();
            this.source_descriptor_lang = new HashSet<source_descriptor_lang>();
        }
    
        public int source_descriptor_id { get; set; }
        public string coded_name { get; set; }
        public string category_code { get; set; }
        public string data_type_code { get; set; }
        public string is_coded { get; set; }
        public Nullable<int> max_length { get; set; }
        public string numeric_format { get; set; }
        public Nullable<decimal> numeric_maximum { get; set; }
        public Nullable<decimal> numeric_minimum { get; set; }
        public string original_value_type_code { get; set; }
        public string original_value_format { get; set; }
        public string ontology_url { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<source_desc_observation> source_desc_observation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<source_descriptor_code> source_descriptor_code { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<source_descriptor_lang> source_descriptor_lang { get; set; }
    }
}
