//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_datatrigger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_datatrigger()
        {
            this.sys_datatrigger_lang = new HashSet<sys_datatrigger_lang>();
        }
    
        public int sys_datatrigger_id { get; set; }
        public Nullable<int> sys_dataview_id { get; set; }
        public Nullable<int> sys_table_id { get; set; }
        public string virtual_file_path { get; set; }
        public string assembly_name { get; set; }
        public string fully_qualified_class_name { get; set; }
        public string is_enabled { get; set; }
        public string is_system { get; set; }
        public int sort_order { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual sys_dataview sys_dataview { get; set; }
        public virtual sys_table sys_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_datatrigger_lang> sys_datatrigger_lang { get; set; }
    }
}
