//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_dataview
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_dataview()
        {
            this.sys_datatrigger = new HashSet<sys_datatrigger>();
            this.sys_dataview_lang = new HashSet<sys_dataview_lang>();
            this.sys_permission = new HashSet<sys_permission>();
            this.sys_dataview_field = new HashSet<sys_dataview_field>();
            this.sys_dataview_param = new HashSet<sys_dataview_param>();
            this.sys_dataview_sql = new HashSet<sys_dataview_sql>();
            this.sys_search_resolver = new HashSet<sys_search_resolver>();
        }
    
        public int sys_dataview_id { get; set; }
        public string dataview_name { get; set; }
        public string is_enabled { get; set; }
        public string is_readonly { get; set; }
        public string category_code { get; set; }
        public string database_area_code { get; set; }
        public Nullable<int> database_area_code_sort_order { get; set; }
        public string is_transform { get; set; }
        public string transform_field_for_names { get; set; }
        public string transform_field_for_captions { get; set; }
        public string transform_field_for_values { get; set; }
        public string configuration_options { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_datatrigger> sys_datatrigger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_dataview_lang> sys_dataview_lang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_permission> sys_permission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_dataview_field> sys_dataview_field { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_dataview_param> sys_dataview_param { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_dataview_sql> sys_dataview_sql { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_search_resolver> sys_search_resolver { get; set; }
    }
}
