//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_permission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_permission()
        {
            this.sys_group_permission_map = new HashSet<sys_group_permission_map>();
            this.sys_permission_field = new HashSet<sys_permission_field>();
            this.sys_permission_lang = new HashSet<sys_permission_lang>();
            this.sys_user_permission_map = new HashSet<sys_user_permission_map>();
        }
    
        public int sys_permission_id { get; set; }
        public Nullable<int> sys_dataview_id { get; set; }
        public Nullable<int> sys_table_id { get; set; }
        public string permission_tag { get; set; }
        public string is_enabled { get; set; }
        public string create_permission { get; set; }
        public string read_permission { get; set; }
        public string update_permission { get; set; }
        public string delete_permission { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual sys_dataview sys_dataview { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_group_permission_map> sys_group_permission_map { get; set; }
        public virtual sys_table sys_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_permission_field> sys_permission_field { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_permission_lang> sys_permission_lang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_user_permission_map> sys_user_permission_map { get; set; }
    }
}
