//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_permission_field
    {
        public int sys_permission_field_id { get; set; }
        public int sys_permission_id { get; set; }
        public Nullable<int> sys_dataview_field_id { get; set; }
        public Nullable<int> sys_table_field_id { get; set; }
        public string field_type { get; set; }
        public string compare_operator { get; set; }
        public string compare_value { get; set; }
        public Nullable<int> parent_table_field_id { get; set; }
        public string parent_field_type { get; set; }
        public string parent_compare_operator { get; set; }
        public string parent_compare_value { get; set; }
        public string compare_mode { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual sys_dataview_field sys_dataview_field { get; set; }
        public virtual sys_permission sys_permission { get; set; }
        public virtual sys_table_field sys_table_field { get; set; }
        public virtual sys_table_field sys_table_field1 { get; set; }
    }
}
