//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_dataview_field
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_dataview_field()
        {
            this.sys_permission_field = new HashSet<sys_permission_field>();
            this.sys_dataview_field_lang = new HashSet<sys_dataview_field_lang>();
        }
    
        public int sys_dataview_field_id { get; set; }
        public int sys_dataview_id { get; set; }
        public string field_name { get; set; }
        public Nullable<int> sys_table_field_id { get; set; }
        public string is_readonly { get; set; }
        public string is_primary_key { get; set; }
        public string is_transform { get; set; }
        public int sort_order { get; set; }
        public string gui_hint { get; set; }
        public string foreign_key_dataview_name { get; set; }
        public string group_name { get; set; }
        public string table_alias_name { get; set; }
        public string is_visible { get; set; }
        public string configuration_options { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual sys_dataview sys_dataview { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_permission_field> sys_permission_field { get; set; }
        public virtual sys_table_field sys_table_field { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_dataview_field_lang> sys_dataview_field_lang { get; set; }
    }
}
