//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_table_field
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_table_field()
        {
            this.sys_dataview_field = new HashSet<sys_dataview_field>();
            this.sys_index_field = new HashSet<sys_index_field>();
            this.sys_permission_field = new HashSet<sys_permission_field>();
            this.sys_permission_field1 = new HashSet<sys_permission_field>();
            this.sys_search_autofield = new HashSet<sys_search_autofield>();
            this.sys_table_field1 = new HashSet<sys_table_field>();
            this.sys_table_field_lang = new HashSet<sys_table_field_lang>();
            this.sys_table_relationship = new HashSet<sys_table_relationship>();
            this.sys_table_relationship1 = new HashSet<sys_table_relationship>();
        }
    
        public int sys_table_field_id { get; set; }
        public int sys_table_id { get; set; }
        public string field_name { get; set; }
        public Nullable<int> field_ordinal { get; set; }
        public string field_purpose { get; set; }
        public string field_type { get; set; }
        public string default_value { get; set; }
        public string is_primary_key { get; set; }
        public string is_foreign_key { get; set; }
        public Nullable<int> foreign_key_table_field_id { get; set; }
        public string foreign_key_dataview_name { get; set; }
        public string is_nullable { get; set; }
        public string gui_hint { get; set; }
        public string is_readonly { get; set; }
        public int min_length { get; set; }
        public int max_length { get; set; }
        public int numeric_precision { get; set; }
        public int numeric_scale { get; set; }
        public string is_autoincrement { get; set; }
        public string group_name { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_dataview_field> sys_dataview_field { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_index_field> sys_index_field { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_permission_field> sys_permission_field { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_permission_field> sys_permission_field1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_search_autofield> sys_search_autofield { get; set; }
        public virtual sys_table sys_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_table_field> sys_table_field1 { get; set; }
        public virtual sys_table_field sys_table_field2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_table_field_lang> sys_table_field_lang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_table_relationship> sys_table_relationship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_table_relationship> sys_table_relationship1 { get; set; }
    }
}
