//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxonomy_crop_map
    {
        public int taxonomy_crop_map_id { get; set; }
        public int taxonomy_species_id { get; set; }
        public int crop_id { get; set; }
        public string alternate_crop_name { get; set; }
        public string common_crop_name { get; set; }
        public string is_primary_genepool { get; set; }
        public string is_secondary_genepool { get; set; }
        public string is_tertiary_genepool { get; set; }
        public string is_quaternary_genepool { get; set; }
        public string is_graftstock_genepool { get; set; }
        public string crop_genepool_reviewers { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual crop crop { get; set; }
        public virtual taxonomy_species taxonomy_species { get; set; }
    }
}
