//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class gringlobal_Entities : DbContext
    {
        public gringlobal_Entities()
            : base("name=gringlobal_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accession> accessions { get; set; }
        public virtual DbSet<accession_action> accession_action { get; set; }
        public virtual DbSet<accession_inv_annotation> accession_inv_annotation { get; set; }
        public virtual DbSet<accession_inv_attach> accession_inv_attach { get; set; }
        public virtual DbSet<accession_inv_group> accession_inv_group { get; set; }
        public virtual DbSet<accession_inv_group_attach> accession_inv_group_attach { get; set; }
        public virtual DbSet<accession_inv_group_map> accession_inv_group_map { get; set; }
        public virtual DbSet<accession_inv_name> accession_inv_name { get; set; }
        public virtual DbSet<accession_inv_voucher> accession_inv_voucher { get; set; }
        public virtual DbSet<accession_ipr> accession_ipr { get; set; }
        public virtual DbSet<accession_pedigree> accession_pedigree { get; set; }
        public virtual DbSet<accession_quarantine> accession_quarantine { get; set; }
        public virtual DbSet<accession_source> accession_source { get; set; }
        public virtual DbSet<accession_source_map> accession_source_map { get; set; }
        public virtual DbSet<app_resource> app_resource { get; set; }
        public virtual DbSet<app_setting> app_setting { get; set; }
        public virtual DbSet<app_user_gui_setting> app_user_gui_setting { get; set; }
        public virtual DbSet<app_user_item_list> app_user_item_list { get; set; }
        public virtual DbSet<citation> citations { get; set; }
        public virtual DbSet<code_value> code_value { get; set; }
        public virtual DbSet<code_value_lang> code_value_lang { get; set; }
        public virtual DbSet<cooperator> cooperators { get; set; }
        public virtual DbSet<cooperator_group> cooperator_group { get; set; }
        public virtual DbSet<cooperator_map> cooperator_map { get; set; }
        public virtual DbSet<crop> crops { get; set; }
        public virtual DbSet<crop_attach> crop_attach { get; set; }
        public virtual DbSet<crop_germplasm_committee> crop_germplasm_committee { get; set; }
        public virtual DbSet<crop_germplasm_committee_crop_descriptor> crop_germplasm_committee_crop_descriptor { get; set; }
        public virtual DbSet<crop_germplasm_committee_document> crop_germplasm_committee_document { get; set; }
        public virtual DbSet<crop_trait> crop_trait { get; set; }
        public virtual DbSet<crop_trait_attach> crop_trait_attach { get; set; }
        public virtual DbSet<crop_trait_code> crop_trait_code { get; set; }
        public virtual DbSet<crop_trait_code_attach> crop_trait_code_attach { get; set; }
        public virtual DbSet<crop_trait_code_lang> crop_trait_code_lang { get; set; }
        public virtual DbSet<crop_trait_lang> crop_trait_lang { get; set; }
        public virtual DbSet<crop_trait_observation> crop_trait_observation { get; set; }
        public virtual DbSet<crop_trait_observation_data> crop_trait_observation_data { get; set; }
        public virtual DbSet<email> emails { get; set; }
        public virtual DbSet<email_attach> email_attach { get; set; }
        public virtual DbSet<exploration> explorations { get; set; }
        public virtual DbSet<exploration_map> exploration_map { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<feedback_attach> feedback_attach { get; set; }
        public virtual DbSet<feedback_form> feedback_form { get; set; }
        public virtual DbSet<feedback_form_field> feedback_form_field { get; set; }
        public virtual DbSet<feedback_form_trait> feedback_form_trait { get; set; }
        public virtual DbSet<feedback_inventory> feedback_inventory { get; set; }
        public virtual DbSet<feedback_report> feedback_report { get; set; }
        public virtual DbSet<feedback_report_attach> feedback_report_attach { get; set; }
        public virtual DbSet<feedback_result> feedback_result { get; set; }
        public virtual DbSet<feedback_result_attach> feedback_result_attach { get; set; }
        public virtual DbSet<feedback_result_field> feedback_result_field { get; set; }
        public virtual DbSet<feedback_result_group> feedback_result_group { get; set; }
        public virtual DbSet<feedback_result_trait_obs> feedback_result_trait_obs { get; set; }
        public virtual DbSet<genetic_annotation> genetic_annotation { get; set; }
        public virtual DbSet<genetic_marker> genetic_marker { get; set; }
        public virtual DbSet<genetic_observation> genetic_observation { get; set; }
        public virtual DbSet<genetic_observation_data> genetic_observation_data { get; set; }
        public virtual DbSet<geneva_site_inventory> geneva_site_inventory { get; set; }
        public virtual DbSet<geography> geographies { get; set; }
        public virtual DbSet<geography_region_map> geography_region_map { get; set; }
        public virtual DbSet<gspi_site_inventory> gspi_site_inventory { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<inventory_action> inventory_action { get; set; }
        public virtual DbSet<inventory_maint_policy> inventory_maint_policy { get; set; }
        public virtual DbSet<inventory_quality_status> inventory_quality_status { get; set; }
        public virtual DbSet<inventory_viability> inventory_viability { get; set; }
        public virtual DbSet<inventory_viability_data> inventory_viability_data { get; set; }
        public virtual DbSet<inventory_viability_rule> inventory_viability_rule { get; set; }
        public virtual DbSet<inventory_viability_rule_map> inventory_viability_rule_map { get; set; }
        public virtual DbSet<literature> literatures { get; set; }
        public virtual DbSet<method> methods { get; set; }
        public virtual DbSet<method_attach> method_attach { get; set; }
        public virtual DbSet<method_map> method_map { get; set; }
        public virtual DbSet<name_group> name_group { get; set; }
        public virtual DbSet<nc7_site_inventory> nc7_site_inventory { get; set; }
        public virtual DbSet<ne9_site_inventory> ne9_site_inventory { get; set; }
        public virtual DbSet<nssl_site_inventory> nssl_site_inventory { get; set; }
        public virtual DbSet<opgc_site_inventory> opgc_site_inventory { get; set; }
        public virtual DbSet<order_request> order_request { get; set; }
        public virtual DbSet<order_request_action> order_request_action { get; set; }
        public virtual DbSet<order_request_attach> order_request_attach { get; set; }
        public virtual DbSet<order_request_item> order_request_item { get; set; }
        public virtual DbSet<order_request_item_action> order_request_item_action { get; set; }
        public virtual DbSet<order_request_phyto_log> order_request_phyto_log { get; set; }
        public virtual DbSet<parl_site_inventory> parl_site_inventory { get; set; }
        public virtual DbSet<plant_immigrant_index> plant_immigrant_index { get; set; }
        public virtual DbSet<plant_inventory> plant_inventory { get; set; }
        public virtual DbSet<plant_inventory_index> plant_inventory_index { get; set; }
        public virtual DbSet<pvpo_catalog> pvpo_catalog { get; set; }
        public virtual DbSet<region> regions { get; set; }
        public virtual DbSet<rhy> rhies { get; set; }
        public virtual DbSet<s9_site_inventory> s9_site_inventory { get; set; }
        public virtual DbSet<site> sites { get; set; }
        public virtual DbSet<source_desc_observation> source_desc_observation { get; set; }
        public virtual DbSet<source_descriptor> source_descriptor { get; set; }
        public virtual DbSet<source_descriptor_code> source_descriptor_code { get; set; }
        public virtual DbSet<source_descriptor_code_lang> source_descriptor_code_lang { get; set; }
        public virtual DbSet<source_descriptor_lang> source_descriptor_lang { get; set; }
        public virtual DbSet<sys_database> sys_database { get; set; }
        public virtual DbSet<sys_database_migration> sys_database_migration { get; set; }
        public virtual DbSet<sys_database_migration_lang> sys_database_migration_lang { get; set; }
        public virtual DbSet<sys_datatrigger> sys_datatrigger { get; set; }
        public virtual DbSet<sys_datatrigger_lang> sys_datatrigger_lang { get; set; }
        public virtual DbSet<sys_dataview> sys_dataview { get; set; }
        public virtual DbSet<sys_dataview_field> sys_dataview_field { get; set; }
        public virtual DbSet<sys_dataview_field_lang> sys_dataview_field_lang { get; set; }
        public virtual DbSet<sys_dataview_lang> sys_dataview_lang { get; set; }
        public virtual DbSet<sys_dataview_param> sys_dataview_param { get; set; }
        public virtual DbSet<sys_dataview_sql> sys_dataview_sql { get; set; }
        public virtual DbSet<sys_file> sys_file { get; set; }
        public virtual DbSet<sys_file_group> sys_file_group { get; set; }
        public virtual DbSet<sys_file_group_map> sys_file_group_map { get; set; }
        public virtual DbSet<sys_file_lang> sys_file_lang { get; set; }
        public virtual DbSet<sys_group> sys_group { get; set; }
        public virtual DbSet<sys_group_lang> sys_group_lang { get; set; }
        public virtual DbSet<sys_group_permission_map> sys_group_permission_map { get; set; }
        public virtual DbSet<sys_group_user_map> sys_group_user_map { get; set; }
        public virtual DbSet<sys_index> sys_index { get; set; }
        public virtual DbSet<sys_index_field> sys_index_field { get; set; }
        public virtual DbSet<sys_lang> sys_lang { get; set; }
        public virtual DbSet<sys_permission> sys_permission { get; set; }
        public virtual DbSet<sys_permission_field> sys_permission_field { get; set; }
        public virtual DbSet<sys_permission_lang> sys_permission_lang { get; set; }
        public virtual DbSet<sys_search_autofield> sys_search_autofield { get; set; }
        public virtual DbSet<sys_search_resolver> sys_search_resolver { get; set; }
        public virtual DbSet<sys_table> sys_table { get; set; }
        public virtual DbSet<sys_table_field> sys_table_field { get; set; }
        public virtual DbSet<sys_table_field_lang> sys_table_field_lang { get; set; }
        public virtual DbSet<sys_table_lang> sys_table_lang { get; set; }
        public virtual DbSet<sys_table_relationship> sys_table_relationship { get; set; }
        public virtual DbSet<sys_user> sys_user { get; set; }
        public virtual DbSet<sys_user_permission_map> sys_user_permission_map { get; set; }
        public virtual DbSet<taxonomy_alt_family_map> taxonomy_alt_family_map { get; set; }
        public virtual DbSet<taxonomy_attach> taxonomy_attach { get; set; }
        public virtual DbSet<taxonomy_author> taxonomy_author { get; set; }
        public virtual DbSet<taxonomy_common_name> taxonomy_common_name { get; set; }
        public virtual DbSet<taxonomy_crop_map> taxonomy_crop_map { get; set; }
        public virtual DbSet<taxonomy_cwr> taxonomy_cwr { get; set; }
        public virtual DbSet<taxonomy_cwr_priority> taxonomy_cwr_priority { get; set; }
        public virtual DbSet<taxonomy_family> taxonomy_family { get; set; }
        public virtual DbSet<taxonomy_genus> taxonomy_genus { get; set; }
        public virtual DbSet<taxonomy_geography_map> taxonomy_geography_map { get; set; }
        public virtual DbSet<taxonomy_noxious> taxonomy_noxious { get; set; }
        public virtual DbSet<taxonomy_species> taxonomy_species { get; set; }
        public virtual DbSet<taxonomy_use> taxonomy_use { get; set; }
        public virtual DbSet<w6_site_inventory> w6_site_inventory { get; set; }
        public virtual DbSet<web_cooperator> web_cooperator { get; set; }
        public virtual DbSet<web_help> web_help { get; set; }
        public virtual DbSet<web_order_request> web_order_request { get; set; }
        public virtual DbSet<web_order_request_action> web_order_request_action { get; set; }
        public virtual DbSet<web_order_request_address> web_order_request_address { get; set; }
        public virtual DbSet<web_order_request_attach> web_order_request_attach { get; set; }
        public virtual DbSet<web_order_request_item> web_order_request_item { get; set; }
        public virtual DbSet<web_user> web_user { get; set; }
        public virtual DbSet<web_user_cart> web_user_cart { get; set; }
        public virtual DbSet<web_user_cart_item> web_user_cart_item { get; set; }
        public virtual DbSet<web_user_preference> web_user_preference { get; set; }
        public virtual DbSet<web_user_shipping_address> web_user_shipping_address { get; set; }
        public virtual DbSet<crop_germplasm_committee_meeting> crop_germplasm_committee_meeting { get; set; }
        public virtual DbSet<pvpo_catalog_bak> pvpo_catalog_bak { get; set; }
    
        public virtual ObjectResult<LP_SEARCH_RHYZOBIUM_Result> LP_SEARCH_RHYZOBIUM(string searchString)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("searchString", searchString) :
                new ObjectParameter("searchString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LP_SEARCH_RHYZOBIUM_Result>("LP_SEARCH_RHYZOBIUM", searchStringParameter);
        }
    }
}
