//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxonomy_species
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public taxonomy_species()
        {
            this.accessions = new HashSet<accession>();
            this.accession_inv_annotation = new HashSet<accession_inv_annotation>();
            this.accession_inv_annotation1 = new HashSet<accession_inv_annotation>();
            this.citations = new HashSet<citation>();
            this.inventory_viability_rule_map = new HashSet<inventory_viability_rule_map>();
            this.taxonomy_attach = new HashSet<taxonomy_attach>();
            this.taxonomy_common_name = new HashSet<taxonomy_common_name>();
            this.taxonomy_crop_map = new HashSet<taxonomy_crop_map>();
            this.taxonomy_cwr = new HashSet<taxonomy_cwr>();
            this.taxonomy_cwr_priority = new HashSet<taxonomy_cwr_priority>();
            this.taxonomy_geography_map = new HashSet<taxonomy_geography_map>();
            this.taxonomy_noxious = new HashSet<taxonomy_noxious>();
            this.taxonomy_species1 = new HashSet<taxonomy_species>();
            this.taxonomy_use = new HashSet<taxonomy_use>();
        }
    
        public int taxonomy_species_id { get; set; }
        public Nullable<int> current_taxonomy_species_id { get; set; }
        public Nullable<int> nomen_number { get; set; }
        public string is_specific_hybrid { get; set; }
        public string species_name { get; set; }
        public string species_authority { get; set; }
        public string is_subspecific_hybrid { get; set; }
        public string subspecies_name { get; set; }
        public string subspecies_authority { get; set; }
        public string is_varietal_hybrid { get; set; }
        public string variety_name { get; set; }
        public string variety_authority { get; set; }
        public string is_subvarietal_hybrid { get; set; }
        public string subvariety_name { get; set; }
        public string subvariety_authority { get; set; }
        public string is_forma_hybrid { get; set; }
        public string forma_rank_type { get; set; }
        public string forma_name { get; set; }
        public string forma_authority { get; set; }
        public int taxonomy_genus_id { get; set; }
        public Nullable<int> priority1_site_id { get; set; }
        public Nullable<int> priority2_site_id { get; set; }
        public Nullable<int> curator1_cooperator_id { get; set; }
        public Nullable<int> curator2_cooperator_id { get; set; }
        public string restriction_code { get; set; }
        public string life_form_code { get; set; }
        public string common_fertilization_code { get; set; }
        public string is_name_pending { get; set; }
        public string synonym_code { get; set; }
        public Nullable<int> verifier_cooperator_id { get; set; }
        public Nullable<System.DateTime> name_verified_date { get; set; }
        public string name { get; set; }
        public string name_authority { get; set; }
        public string protologue { get; set; }
        public string protologue_virtual_path { get; set; }
        public string note { get; set; }
        public string site_note { get; set; }
        public string alternate_name { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accession> accessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accession_inv_annotation> accession_inv_annotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accession_inv_annotation> accession_inv_annotation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<citation> citations { get; set; }
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual cooperator cooperator3 { get; set; }
        public virtual cooperator cooperator4 { get; set; }
        public virtual cooperator cooperator5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_viability_rule_map> inventory_viability_rule_map { get; set; }
        public virtual site site { get; set; }
        public virtual site site1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taxonomy_attach> taxonomy_attach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taxonomy_common_name> taxonomy_common_name { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taxonomy_crop_map> taxonomy_crop_map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taxonomy_cwr> taxonomy_cwr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taxonomy_cwr_priority> taxonomy_cwr_priority { get; set; }
        public virtual taxonomy_genus taxonomy_genus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taxonomy_geography_map> taxonomy_geography_map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taxonomy_noxious> taxonomy_noxious { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taxonomy_species> taxonomy_species1 { get; set; }
        public virtual taxonomy_species taxonomy_species2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taxonomy_use> taxonomy_use { get; set; }
    }
}
