//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxonomy_common_name
    {
        public int taxonomy_common_name_id { get; set; }
        public Nullable<int> taxonomy_genus_id { get; set; }
        public Nullable<int> taxonomy_species_id { get; set; }
        public string language_description { get; set; }
        public string name { get; set; }
        public string simplified_name { get; set; }
        public string alternate_transcription { get; set; }
        public Nullable<int> citation_id { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual citation citation { get; set; }
        public virtual cooperator cooperator { get; set; }
        public virtual cooperator cooperator1 { get; set; }
        public virtual cooperator cooperator2 { get; set; }
        public virtual taxonomy_genus taxonomy_genus { get; set; }
        public virtual taxonomy_species taxonomy_species { get; set; }
    }
}
