//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public web_user()
        {
            this.web_cooperator = new HashSet<web_cooperator>();
            this.web_cooperator1 = new HashSet<web_cooperator>();
            this.web_cooperator2 = new HashSet<web_cooperator>();
            this.web_order_request = new HashSet<web_order_request>();
            this.web_order_request1 = new HashSet<web_order_request>();
            this.web_order_request_action = new HashSet<web_order_request_action>();
            this.web_order_request_action1 = new HashSet<web_order_request_action>();
            this.web_order_request_action2 = new HashSet<web_order_request_action>();
            this.web_order_request_address = new HashSet<web_order_request_address>();
            this.web_order_request_address1 = new HashSet<web_order_request_address>();
            this.web_order_request_address2 = new HashSet<web_order_request_address>();
            this.web_order_request_attach = new HashSet<web_order_request_attach>();
            this.web_order_request_attach1 = new HashSet<web_order_request_attach>();
            this.web_order_request_attach2 = new HashSet<web_order_request_attach>();
            this.web_order_request_item = new HashSet<web_order_request_item>();
            this.web_order_request_item1 = new HashSet<web_order_request_item>();
            this.web_order_request_item2 = new HashSet<web_order_request_item>();
            this.web_user_cart = new HashSet<web_user_cart>();
            this.web_user_cart1 = new HashSet<web_user_cart>();
            this.web_user_cart2 = new HashSet<web_user_cart>();
            this.web_user_cart3 = new HashSet<web_user_cart>();
            this.web_user_cart_item = new HashSet<web_user_cart_item>();
            this.web_user_cart_item1 = new HashSet<web_user_cart_item>();
            this.web_user_cart_item2 = new HashSet<web_user_cart_item>();
            this.web_user_preference = new HashSet<web_user_preference>();
            this.web_user_preference1 = new HashSet<web_user_preference>();
            this.web_user_preference2 = new HashSet<web_user_preference>();
            this.web_user_preference3 = new HashSet<web_user_preference>();
            this.web_user_shipping_address = new HashSet<web_user_shipping_address>();
            this.web_user_shipping_address1 = new HashSet<web_user_shipping_address>();
            this.web_user_shipping_address2 = new HashSet<web_user_shipping_address>();
            this.web_user_shipping_address3 = new HashSet<web_user_shipping_address>();
        }
    
        public int web_user_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string is_enabled { get; set; }
        public int sys_lang_id { get; set; }
        public Nullable<System.DateTime> last_login_date { get; set; }
        public Nullable<int> web_cooperator_id { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    
        public virtual sys_lang sys_lang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_cooperator> web_cooperator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_cooperator> web_cooperator1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_cooperator> web_cooperator2 { get; set; }
        public virtual web_cooperator web_cooperator3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request> web_order_request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request> web_order_request1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request_action> web_order_request_action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request_action> web_order_request_action1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request_action> web_order_request_action2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request_address> web_order_request_address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request_address> web_order_request_address1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request_address> web_order_request_address2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request_attach> web_order_request_attach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request_attach> web_order_request_attach1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request_attach> web_order_request_attach2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request_item> web_order_request_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request_item> web_order_request_item1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request_item> web_order_request_item2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user_cart> web_user_cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user_cart> web_user_cart1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user_cart> web_user_cart2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user_cart> web_user_cart3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user_cart_item> web_user_cart_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user_cart_item> web_user_cart_item1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user_cart_item> web_user_cart_item2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user_preference> web_user_preference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user_preference> web_user_preference1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user_preference> web_user_preference2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user_preference> web_user_preference3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user_shipping_address> web_user_shipping_address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user_shipping_address> web_user_shipping_address1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user_shipping_address> web_user_shipping_address2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user_shipping_address> web_user_shipping_address3 { get; set; }
    }
}
