//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_user_cart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public web_user_cart()
        {
            this.web_user_cart_item = new HashSet<web_user_cart_item>();
        }
    
        public int web_user_cart_id { get; set; }
        public int web_user_id { get; set; }
        public string cart_type_code { get; set; }
        public System.DateTime expiration_date { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual web_user web_user { get; set; }
        public virtual web_user web_user1 { get; set; }
        public virtual web_user web_user2 { get; set; }
        public virtual web_user web_user3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user_cart_item> web_user_cart_item { get; set; }
    }
}
