//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_order_request_address
    {
        public int web_order_request_address_id { get; set; }
        public int web_order_request_id { get; set; }
        public string address_line1 { get; set; }
        public string address_line2 { get; set; }
        public string address_line3 { get; set; }
        public string city { get; set; }
        public string postal_index { get; set; }
        public Nullable<int> geography_id { get; set; }
        public string carrier { get; set; }
        public string carrier_account { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual geography geography { get; set; }
        public virtual web_order_request web_order_request { get; set; }
        public virtual web_user web_user { get; set; }
        public virtual web_user web_user1 { get; set; }
        public virtual web_user web_user2 { get; set; }
    }
}
