//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_order_request_item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public web_order_request_item()
        {
            this.order_request_item = new HashSet<order_request_item>();
        }
    
        public int web_order_request_item_id { get; set; }
        public int web_cooperator_id { get; set; }
        public int web_order_request_id { get; set; }
        public int sequence_number { get; set; }
        public int accession_id { get; set; }
        public string name { get; set; }
        public Nullable<int> quantity_shipped { get; set; }
        public string unit_of_shipped_code { get; set; }
        public string distribution_form_code { get; set; }
        public string status_code { get; set; }
        public string curator_note { get; set; }
        public string user_note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        public virtual accession accession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_request_item> order_request_item { get; set; }
        public virtual web_cooperator web_cooperator { get; set; }
        public virtual web_order_request web_order_request { get; set; }
        public virtual web_user web_user { get; set; }
        public virtual web_user web_user1 { get; set; }
        public virtual web_user web_user2 { get; set; }
    }
}
