//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA.ARS.GRIN.Admin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_cooperator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public web_cooperator()
        {
            this.cooperators = new HashSet<cooperator>();
            this.web_order_request = new HashSet<web_order_request>();
            this.web_order_request_action = new HashSet<web_order_request_action>();
            this.web_order_request_attach = new HashSet<web_order_request_attach>();
            this.web_order_request_item = new HashSet<web_order_request_item>();
            this.web_user3 = new HashSet<web_user>();
        }
    
        public int web_cooperator_id { get; set; }
        public string last_name { get; set; }
        public string title { get; set; }
        public string first_name { get; set; }
        public string job { get; set; }
        public string organization { get; set; }
        public string organization_code { get; set; }
        public string address_line1 { get; set; }
        public string address_line2 { get; set; }
        public string address_line3 { get; set; }
        public string city { get; set; }
        public string postal_index { get; set; }
        public Nullable<int> geography_id { get; set; }
        public string primary_phone { get; set; }
        public string secondary_phone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string is_active { get; set; }
        public string category_code { get; set; }
        public string organization_region { get; set; }
        public string discipline { get; set; }
        public string initials { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public System.DateTime owned_date { get; set; }
        public int owned_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cooperator> cooperators { get; set; }
        public virtual geography geography { get; set; }
        public virtual web_user web_user { get; set; }
        public virtual web_user web_user1 { get; set; }
        public virtual web_user web_user2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request> web_order_request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request_action> web_order_request_action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request_attach> web_order_request_attach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_order_request_item> web_order_request_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_user> web_user3 { get; set; }
    }
}
