CREATE TABLE [taxonomy_ista_seed] (
    [taxonomy_ista_seed_id]        INT            IDENTITY (1, 1) NOT NULL,
    [taxonomy_species_id]          INT            NULL,
    [name_status]                  NVARCHAR (20)  NULL,
    [accepted_taxonomy_species_id] INT            NULL,
    [primary_family_id]            INT            NULL,
    [alternate_family_id_1]        INT            NULL,
    [alternate_family_id_2]        INT            NULL,
    [alternate_family_id_3]        INT            NULL,
    [url]                          NVARCHAR (250) NULL,
    [note]                         NVARCHAR (250) NULL,
    [comment]                      NVARCHAR (250) NULL,
    [taxonomy_upov_crop_map_id]    INT            NULL,
    [created_date]                 DATETIME2 (7)  CONSTRAINT [DF_taxonomy_ista_seed_created_date] DEFAULT (getdate()) NOT NULL,
    [created_by]                   INT            NOT NULL,
    [modified_date]                DATETIME2 (7)  CONSTRAINT [DF_taxonomy_ista_seed_modified_date] DEFAULT (getdate()) NULL,
    [modified_by]                  INT            NULL,
    [owned_date]                   DATETIME2 (7)  CONSTRAINT [DF_taxonomy_ista_seed_owned_date] DEFAULT (getdate()) NOT NULL,
    [owned_by]                     INT            NOT NULL,
    [family_id_2]                  INT            NULL,
    [family_id_3]                  INT            NULL,
    [taxonomy_genus_id]            INT            NULL,
    [taxonomy_upov_crop_id]        INT            NULL,
    [TEMP_UPOV]                    NVARCHAR (50)  NULL,
    [primary_family_name]          NVARCHAR (50)  NULL,
    [family_name_2]                NVARCHAR (50)  NULL,
    CONSTRAINT [PK_taxonomy_upov_seed] PRIMARY KEY CLUSTERED ([taxonomy_ista_seed_id] ASC),
    CONSTRAINT [FK_taxonomy_ista_seed_taxonomy_family] FOREIGN KEY ([primary_family_id]) REFERENCES [taxonomy_family] ([taxonomy_family_id]),
    CONSTRAINT [FK_taxonomy_ista_seed_taxonomy_family1] FOREIGN KEY ([alternate_family_id_1]) REFERENCES [taxonomy_family] ([taxonomy_family_id]),
    CONSTRAINT [FK_taxonomy_ista_seed_taxonomy_family2] FOREIGN KEY ([alternate_family_id_2]) REFERENCES [taxonomy_family] ([taxonomy_family_id]),
    CONSTRAINT [FK_taxonomy_ista_seed_taxonomy_family3] FOREIGN KEY ([alternate_family_id_3]) REFERENCES [taxonomy_family] ([taxonomy_family_id]),
    CONSTRAINT [FK_taxonomy_ista_seed_taxonomy_genus] FOREIGN KEY ([taxonomy_genus_id]) REFERENCES [taxonomy_genus] ([taxonomy_genus_id]),
    CONSTRAINT [FK_taxonomy_ista_seed_taxonomy_ref_upov_crop] FOREIGN KEY ([taxonomy_upov_crop_id]) REFERENCES [taxonomy_ref_upov_crop] ([taxonomy_ref_upov_crop_id]),
    CONSTRAINT [FK_taxonomy_ista_seed_taxonomy_species] FOREIGN KEY ([taxonomy_species_id]) REFERENCES [taxonomy_species] ([taxonomy_species_id])
);

